service: ventrek-bookings

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2
functions:
  graphql:
    handler: src/index.graphqlHandler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"
